services:
    app:
        image: emars-app
        build:
            args:
                user: harry
                uid: 1000
            context: ./
            dockerfile: Dockerfile.dev
        container_name: emars-app
        working_dir: /var/www/
        restart: unless-stopped
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        volumes:
            - ./:/var/www
        networks:
            - skripsinet
        depends_on:
            - redis

    nginx:
        image: nginx:alpine
        container_name: nginx_emars
        restart: unless-stopped
        depends_on:
            - app

        ports:
            # - "8182:80"
            - "8190:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - skripsinet
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

    redis:
        image: redis:7
        container_name: redis-server-emars
        restart: unless-stopped
        volumes:
            - redis_data:/data
        ports:
            - "26758:6379"
        networks:
            - skripsinet

volumes:
    mysql_data:
    redis_data:

networks:
    skripsinet:
        driver: bridge
